### ISSUE TITLE
Dashbuilder echarts displayer shows black horizontal bar when loading charts that are not the demo bar chart

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#2081]
<img width="2591" alt="image" src="https://github.com/kiegroup/kie-tools/assets/1994838/cc14675d-0c46-4d50-84ea-b141219cdc68">

using chrome.

```yaml
datasets:
  - uuid: products
    content: >-
      [
        ["Computers", "Scanner", 5, 3],
        ["Computers", "Printer", 7, 4],
        ["Computers", "Laptop", 3, 2],
        ["Electronics", "Camera", 10, 7],
        ["Electronics", "Headphones", 5, 9]
      ]
    columns:
      - id: Section
      - id: Product
      - id: Quantity
        type: NUMBER
      - id: Quantity2
        type: NUMBER
pages:
- components:
    - displayer:
        component: echarts
        echarts:
            option: >-
                {
                "legend": {
                    "top": "bottom"
                },
                "toolbox": {
                    "show": true,
                    "feature": {
                    "mark": { "show": true },
                    "dataView": { "show": true, "readOnly": false },
                    "restore": { "show": true },
                    "saveAsImage": { "show": true }
                    }
                },
                "series": [
                    {
                    "name": "Nightingale Chart",
                    "type": "pie",
                    "radius": [50, 250],
                    "center": ["50%", "50%"],
                    "roseType": "area",
                    "itemStyle": {
                        "borderRadius": 8
                    }
                    }
                ]
                }
            title:
                text: Products
        external:
          width: 100%
        lookup:
          uuid: products
          group:
            - columnGroup:
                source: Product
              functions:
                - source: Product
                - source: Quantity
                - source: Quantity2
```
