### ISSUE TITLE
VS Code: unnecessary cross for the Serverless workflow diagram

### ISSUE THREAD

**Issue by shootsoft** [apache/incubator-kie-tools#2221]
In some cases, the rendered Serverless workflow diagram has unnecessary cross

![vscode-bug](https://github.com/apache/incubator-kie-tools/assets/797992/83d1c9db-01a3-4520-a86c-e4015e0e6135)

Example Serverless workflow

```yaml
id: VSCodeUnecessaryCorssCross
specVersion: "0.8"
version: "1.0"
name: test
description: show the unnecessary cross issue
start: StartAction

functions:
  - name: log
    type: custom
    operation: sysout:INFO

events:
  - name: BeginEvent
    source: ""
    type: begin-event
  - name: ChangeEvent
    source: ""
    type: change-event


states:
  - name: StartAction
    type: event
    onEvents:
      - eventRefs:
          - begin-event
        actions:
          - name: begin
            functionRef:
              refName: log
              arguments:
                message: Start executing
    transition: parallelCreation

  - name: parallelCreation
    type: parallel
    branches:
      - name: create1
        actions:
          - functionRef:
              refName: log
              arguments:
                message: Creating1
      - name: create2
        actions:
          - functionRef:
              refName: log
              arguments:
                message: Creating2
    numCompleted: "2"
    transition: next

  - name: next
    type: operation
    actions:
      - functionRef:
          refName: log
          arguments:
            message: finishing
    end: true

  - name: changeEvent
    type: event
    onEvents:
      - eventRefs:
          - ChangeEvent
        actions:
          - functionRef:
              refName: log
              arguments:
                message: changing
    transition: hasFlag

  - name: hasFlag
    type: switch
    dataConditions:
      - name: Checking if there is falg.
        condition: .hasFlag
        transition: hasFlagYes
    defaultCondition:
      transition: hasFlagNo

  - name: hasFlagYes
    type: operation
    actions:
      - functionRef:
          refName: log
          arguments:
            message: Has flag
    end: true

  - name: hasFlagNo
    type: operation
    actions:
      - functionRef:
          refName: log
          arguments:
            message: Has no falg.
    end: true
```
