### ISSUE TITLE
Extend the single file import to multiple files (DMN) on KIE Sandbox

### ISSUE THREAD

**Issue by dmitry-buykin** [apache/incubator-kie-tools#2418]
I'm using sandbox image to illustrate a specific file, by attaching my local folder to the sandbox container:
```
  kie_sandbox:
    container_name: kie_sandbox
    volumes:
      - ${PROJECT_HOME}:/var/www/html/samples
```
http://localhost:9090/#/import?url=http://localhost:9090/samples/dmns/primary.dmn

Unfortunately, I cannot import multiple files, which can be great for complex use cases.
I don't want to use github to host these examples, because I need it for a local development environment.

Is it possible to extend `/#/import` endpoint to support upload of multiple pre-defined files (or all files in the directory URL).
