### ISSUE TITLE
[sonataflow-operator] Remove hardcoded version in SonataFlow Operator/CLI artifacts

### ISSUE THREAD

**Issue by ricardozanini** [apache/incubator-kie-tools#2751]
Force versions to come from the `kogito-versions` modules. For example, the operator configuration files should not enable version overriding like:

```yaml
postgreSQLPersistenceExtensions:
  - groupId: io.quarkus
    artifactId: quarkus-jdbc-postgresql
    version: 3.8.6
  - groupId: io.quarkus
    artifactId: quarkus-agroal
    version: 3.8.6
  - groupId: org.kie
    artifactId: kie-addons-quarkus-persistence-jdbc
    version: 999-20241016-SNAPSHOT
```

Each images from Kogito/SonataFlow also must have the platform version defined. See Data Index for example:

```shell
GECOS=JBoss user
HOME=/home/kogito
HOSTNAME=9c853adaa11a
JAVA_DATA_DIR=/deployments/data
JAVA_HOME=/usr/lib/jvm/jre
JAVA_VENDOR=openjdk
JAVA_VERSION=17
JBOSS_CONTAINER_JAVA_JVM_MODULE=/opt/jboss/container/java/jvm
JBOSS_CONTAINER_JAVA_PROXY_MODULE=/opt/jboss/container/java/proxy
JBOSS_CONTAINER_JAVA_RUN_MODULE=/opt/jboss/container/java/run
JBOSS_CONTAINER_OPENJDK_JRE_MODULE=/opt/jboss/container/openjdk/jre
JBOSS_CONTAINER_UTIL_LOGGING_MODULE=/opt/jboss/container/util/logging/
JBOSS_IMAGE_NAME=ubi8/openjdk-17-runtime
JBOSS_IMAGE_VERSION=1.20
KOGITO_DATA_INDEX_QUARKUS_PROFILE=http-events-support
KOGITO_HOME=/home/kogito
LANG=C.utf8
PATH=/home/kogito/.local/bin:/home/kogito/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/kogito
SHLVL=1
TERM=xterm
UID=185
USER=kogito
USER_ID=1001
_=/usr/bin/env
container=oci
```
