### ISSUE TITLE
kn-workflow-plugin fails to minify github spec file

### ISSUE THREAD

**Issue by masayag** [apache/incubator-kie-tools#2908]
Trying to run the `kn-workflow specs minify openapi` for a workflow that uses a single API from 
https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.yaml
That spec file size is > 7MB.

**Reproducer:**
https://github.com/masayag/gh-specs-minify-reproducer/tree/main

```
kn-workflow specs minify openapi 
✅ Minified file /home/masayag/work/orchestrator-demo/01_basic/src/main/resources/specs/test.min.yaml created with 102535 bytes (original size: 105535 bytes)
Error: ❌ ERROR: Minification of /home/masayag/work/orchestrator-demo/01_basic/src/main/resources/specs/github.yaml failed: ❌ ERROR: Minified file /home/masayag/work/orchestrator-demo/01_basic/src/main/resources/specs/github.min.yaml exceeds the size limit of 3145728 bytes
Usage:
  kn workflow specs minify openapi [flags]

Examples:

	#Minify the workflow project's OpenAPI spec file located in the current project.
	{{.Name}} specs minify openapi

	# Specify a custom subflows files directory. (default: ./subflows)
	{{.Name}} specs minify openapi --subflows-dir=<full_directory_path>

	# Specify a custom support specs directory. (default: ./specs)
	{{.Name}} specs minify openapi --specs-dir=<full_directory_path>
		

Flags:
  -h, --help                  help for openapi
  -p, --specs-dir string      Specify a custom specs files directory
  -s, --subflows-dir string   Specify a custom subflows files directory

❌ ERROR: Minification of /home/masayag/work/orchestrator-demo/01_basic/src/main/resources/specs/github.yaml failed: ❌ ERROR: Minified file /home/masayag/work/orchestrator-demo/01_basic/src/main/resources/specs/github.min.yaml exceeds the size limit of 3145728 bytes
```

The workflow definition is:
```yaml
id: basic
version: "1.0"
specVersion: "0.8"
name: "basic"
description: GH tests
dataInputSchema: schemas/basic__main-schema.json
functions:
  - name: getLatestSHA
    operation: specs/github.yaml#getLatestSHA
  - name: createBranch
    operation: specs/github.yaml#createBranch
  - name: createFile
    operation: specs/github.yaml#createFile
  - name: createPullRequest
    operation: specs/github.yaml#createPullRequest
start: "CreateBranch"
states:
  - name: CreateBranch
    type: operation
    actions:
      - name: "GetHeadSha"
        functionRef:
          refName: getLatestSHA
          arguments:  
            owner: .owner
            repo: .repo
            branch: .baseBranch
        actionDataFilter:
          toStateData: .latestSHA
      - name: "createBranch"
        functionRef:
          refName: createBranch
          arguments:  
            owner: .owner
            repo: .repo
            ref: '"refs/heads/" + .targetBranch'
            sha: .latestSHA.object.sha
    transition: CreateFiles
  - name: CreateFiles
    type: foreach
    inputCollection: "${ [.scafolderReponse.files[]] }"
    iterationParam: currentFile
    actions:
      - name: "createFile"
        functionRef:
          refName: createFile
          arguments:  
            owner: .owner
            repo: .repo
            path: .currentFile.path
            message: '"Updating file: " + .currentFile.path'
            content: .currentFile.content | @base64
            branch: .targetBranch
    transition: CreatePR
  - name: CreatePR
    type: operation
    actions:
      - name: "createPullRequest"
        functionRef:
          refName: createPullRequest
          arguments:  
            owner: .owner
            repo: .repo
            title: "Automated PR"
            body: ""
            head: .targetBranch
            base: .baseBranch
        actionDataFilter:
          toStateData: .prURL   
      - name: setOutput
        functionRef:
          refName: successResult
    end: true
```
