### ISSUE TITLE
[sonataflow-operator] DI and JS operator managed deployments are not applying user provided env configuration

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-tools#2938]
When the user defines a SonataFlowPlatform like this:

```
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    dataIndex:
      enabled: true
      podTemplate:
        containers:
          - name: data-index-service
            env:
              - name: QUARKUS_HTTP_CORS
                value: "true"
              - name: QUARKUS_HTTP_CORS_ORIGINS
                value: https://data-index-route-tls-usecase3-platform-persistence-oc.apps-crc.testing
        replicas: 1
    jobService:
      enabled: true
```

The expectation is that user provided env configuration:

```
            env:
              - name: QUARKUS_HTTP_CORS
                value: "true"
              - name: QUARKUS_HTTP_CORS_ORIGINS
                value: https://data-index-route-tls-usecase3-platform-persistence-oc.apps-crc.testing
```

Should added to the corresponding Deployment/Pod. This facilitates potential fine-tunings of any of these services. However, it is not.

We must add that ability, at the same time of evaluating how to deal with potential clashing between user provided and operator managed configurations.
