### ISSUE TITLE
[sonataflow-operator] SonataFlowPlatform status and controller enhancements

### ISSUE THREAD

**Issue by wmedvede** [apache/incubator-kie-tools#3056]
Provide the implementation the enhancements according with: #3054 

Below goes some snippets of proposed updates to the SonataFlowPlatform status.

```
# OpenShift cluster installation happy path, DI (enabled==true),
# and JS (enabled==true), and were deployed successfully
status:
 custer: openshift
 conditions:
 - type: Succeed
   status: "True"
 - type: DataIndexSucceed
   status: "True"
   reason: ServiceEnabled
 - type: JobsServiceSucceed
   status: "True"
   reason: ServiceEnabled
```

```
# OpenShift cluster intermediate step, DI is in the middle of the
# deployment process and JS didn't start yet.
status:
 custer: openshift
 conditions:
 - type: Succeed
   status: "False"
 - type: DataIndexSucceed
   status: "False"
   reason: WaitingForDBMigration
 - type: JobsServiceSucceed
   status: "False"
   reason: WaitingToStartDeployment
```

```
# OpenShit cluster failure path, DI was deployed ok, but JS
# deployment has failed.
status:
 custer: openshift
 conditions:
 - type: Succeed
   status: "False"
   reason: JobsServiceFailure
 - type: DataIndexSucceed
   status: "True"
   reason: ServiceEnabled
 - type: JobsServiceSucceed
   status: "False"
   reason: DBMigrationFailure
   message: An error was produced when creating table my-jobs etc, etc...
```
